# Configuration of app parameters

database:
  base_dir: "data/database"
  name: "chroma"
  document_base_path: "data"
  number_search_results: 5

splitter:
  chunk_overlap: 256
  chunk_size: 1024

embedding:
  model: "text-embedding-ada-002"

# OpenAI
llm:
  provider: "openai"
  model: "gpt-3.5-turbo"

# AzureOpenAI
# llm:
#   provider: "azure"
#   model: "gpt-3.5-turbo"
#   endpoint: ""
#   api_version: ""
