name: GitHub CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Code quality checks
    
    env:
      OPENAI_API_KEY: "verysecretkey"
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Run black code formatter
      run: find ragcore -name "*.py" -exec black {} +

    - name: Run mypy on source folder
      run:  mypy ragcore/

    - name: Run pylint
      run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
